server: 
  port: 11000 
   
spring:
  application:
    name:  microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/java1234/microservice-config
spring: 
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
port: 111
---
spring:
  profiles: test
port: 222
